name: ennui_dev
channels:
  - defaults
dependencies:
  - cmake>=3.20
  - python>=3.12
  - pip>=24.0
  - pip:
      - conan>=2.6.0
      # python binding
      - nanobind
      - scikit-build-core-conan
      - setuptools>=69.5.1
      # development
      - pre-commit>=3.8.0
      # documentation
      - -r docs/requirements.txt
      # demos
      - numpy
